/**
 * IPC Actions
 * */
const IPC_LIST_PAIRED_DEVICES = 'IPC_LIST_PAIRED_DEVICES';
const IPC_LIST_PAIRED_DEVICES_SUCCESS = 'IPC_LIST_PAIRED_DEVICES_SUCCESS';
const IPC_LIST_PAIRED_DEVICES_FAILURE = 'IPC_LIST_PAIRED_DEVICES_FAILURE';
const IPC_CONNECT_DEVICE = 'IPC_CONNECT_DEVICE';
const IPC_CONNECT_DEVICE_SUCCESS = 'IPC_CONNECT_DEVICE_SUCCESS';
const IPC_CONNECT_DEVICE_FAILURE = 'IPC_CONNECT_DEVICE_FAILURE';
const IPC_DISCONNECT_DEVICE = 'IPC_DISCONNECT_DEVICE';
const IPC_DISCONNECT_DEVICE_SUCCESS = 'IPC_DISCONNECT_DEVICE_SUCCESS';
const IPC_DISCONNECT_DEVICE_FAILURE = 'IPC_DISCONNECT_DEVICE_FAILURE';
const IPC_READ_DEVICE_DATA = 'IPC_READ_DEVICE_DATA';
const IPC_READ_DEVICE_DATA_SUCCESS = 'IPC_READ_DEVICE_DATA_SUCCESS';
const IPC_READ_DEVICE_DATA_FAILURE = 'IPC_READ_DEVICE_DATA_FAILURE';
const IPC_WRITE_DEVICE_DATA = 'IPC_WRITE_DEVICE_DATA';
const IPC_WRITE_DEVICE_DATA_SUCCESS = 'IPC_WRITE_DEVICE_DATA_SUCCESS';
const IPC_WRITE_DEVICE_DATA_FAILURE = 'IPC_WRITE_DEVICE_DATA_FAILURE';

const ipc = {
	IPC_LIST_PAIRED_DEVICES,
	IPC_LIST_PAIRED_DEVICES_SUCCESS,
	IPC_LIST_PAIRED_DEVICES_FAILURE,
	IPC_CONNECT_DEVICE,
	IPC_CONNECT_DEVICE_SUCCESS,
	IPC_CONNECT_DEVICE_FAILURE,
	IPC_DISCONNECT_DEVICE,
	IPC_DISCONNECT_DEVICE_SUCCESS,
	IPC_DISCONNECT_DEVICE_FAILURE,
	IPC_READ_DEVICE_DATA,
	IPC_READ_DEVICE_DATA_SUCCESS,
	IPC_READ_DEVICE_DATA_FAILURE,
	IPC_WRITE_DEVICE_DATA,
	IPC_WRITE_DEVICE_DATA_SUCCESS,
	IPC_WRITE_DEVICE_DATA_FAILURE
};

module.exports = ipc;