/**
 * IPC Actions
 * */
const IPC_FETCH_PAIRED_DEVICES = 'IPC_FETCH_PAIRED_DEVICES';
const IPC_FETCH_PAIRED_DEVICES_SUCCESS = 'IPC_FETCH_PAIRED_DEVICES_SUCCESS';
const IPC_FETCH_PAIRED_DEVICES_FAILURE = 'IPC_FETCH_PAIRED_DEVICES_FAILURE';

const IPC_SCAN_ACTIVE_DEVICES = 'IPC_SCAN_ACTIVE_DEVICES';
const IPC_SCAN_ACTIVE_DEVICES_SUCCESS = 'IPC_SCAN_ACTIVE_DEVICES_SUCCESS';
const IPC_SCAN_ACTIVE_DEVICES_FAILURE = 'IPC_SCAN_ACTIVE_DEVICES_FAILURE';

const IPC_CONNECT_TO_DEVICE = 'IPC_CONNECT_TO_DEVICE';
const IPC_CONNECT_TO_DEVICE_SUCCESS = 'IPC_CONNECT_TO_DEVICE_SUCCESS';
const IPC_CONNECT_TO_DEVICE_FAILURE = 'IPC_CONNECT_TO_DEVICE_FAILURE';

const IPC_DISCONNECT_FROM_DEVICE = 'IPC_DISCONNECT_FROM_DEVICE';
const IPC_DISCONNECT_FROM_DEVICE_SUCCESS = 'IPC_DISCONNECT_FROM_DEVICE_SUCCESS';
const IPC_DISCONNECT_FROM_DEVICE_FAILURE = 'IPC_DISCONNECT_FROM_DEVICE_FAILURE';

const IPC_READ_DATA_FROM_DEVICE = 'IPC_READ_DATA_FROM_DEVICE';
const IPC_READ_DATA_FROM_DEVICE_SUCCESS = 'IPC_READ_DATA_FROM_DEVICE_SUCCESS';
const IPC_READ_DATA_FROM_DEVICE_FAILURE = 'IPC_READ_DATA_FROM_DEVICE_FAILURE';

const IPC_WRITE_DATA_TO_DEVICE = 'IPC_WRITE_DATA_TO_DEVICE';
const IPC_WRITE_DATA_TO_DEVICE_SUCCESS = 'IPC_WRITE_DATA_TO_DEVICE_SUCCESS';
const IPC_WRITE_DATA_TO_DEVICE_FAILURE = 'IPC_WRITE_DATA_TO_DEVICE_FAILURE';

const ipc = {
	IPC_FETCH_PAIRED_DEVICES,
	IPC_FETCH_PAIRED_DEVICES_SUCCESS,
	IPC_FETCH_PAIRED_DEVICES_FAILURE,
	IPC_SCAN_ACTIVE_DEVICES,
	IPC_SCAN_ACTIVE_DEVICES_SUCCESS,
	IPC_SCAN_ACTIVE_DEVICES_FAILURE,
	IPC_CONNECT_TO_DEVICE,
	IPC_CONNECT_TO_DEVICE_SUCCESS,
	IPC_CONNECT_TO_DEVICE_FAILURE,
	IPC_DISCONNECT_FROM_DEVICE,
	IPC_DISCONNECT_FROM_DEVICE_SUCCESS,
	IPC_DISCONNECT_FROM_DEVICE_FAILURE,
	IPC_READ_DATA_FROM_DEVICE,
	IPC_READ_DATA_FROM_DEVICE_SUCCESS,
	IPC_READ_DATA_FROM_DEVICE_FAILURE,
	IPC_WRITE_DATA_TO_DEVICE,
	IPC_WRITE_DATA_TO_DEVICE_SUCCESS,
	IPC_WRITE_DATA_TO_DEVICE_FAILURE
};

module.exports = ipc;